package com.whut.model;
// default package
// Generated 2019-7-1 16:23:34 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NewsInfo generated by hbm2java
 */
@Entity
@Table(name = "news_info", catalog = "cloudtest")
public class NewsInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer newsId;
	private String newsTitle;
	private String newsAuthor;
	private String newsTime;
	private String newsContent;
	private Integer newsPriority;
	private String newsPublisher;
	private Integer newsClickNum;
	private String newsType;
	private String reserve1;
	private String reserve2;

	public NewsInfo() {
	}

	public NewsInfo(String newsTitle, String newsAuthor, String newsTime, String newsContent, Integer newsPriority,
			String newsPublisher, Integer newsClickNum, String newsType, String reserve1, String reserve2) {
		this.newsTitle = newsTitle;
		this.newsAuthor = newsAuthor;
		this.newsTime = newsTime;
		this.newsContent = newsContent;
		this.newsPriority = newsPriority;
		this.newsPublisher = newsPublisher;
		this.newsClickNum = newsClickNum;
		this.newsType = newsType;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "newsId", unique = true, nullable = false)
	public Integer getNewsId() {
		return this.newsId;
	}

	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}

	@Column(name = "newsTitle", length = 100)
	public String getNewsTitle() {
		return this.newsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}

	@Column(name = "newsAuthor", length = 100)
	public String getNewsAuthor() {
		return this.newsAuthor;
	}

	public void setNewsAuthor(String newsAuthor) {
		this.newsAuthor = newsAuthor;
	}

	@Column(name = "newsTime", length = 50)
	public String getNewsTime() {
		return this.newsTime;
	}

	public void setNewsTime(String newsTime) {
		this.newsTime = newsTime;
	}

	@Column(name = "newsContent")
	public String getNewsContent() {
		return this.newsContent;
	}

	public void setNewsContent(String newsContent) {
		this.newsContent = newsContent;
	}

	@Column(name = "newsPriority")
	public Integer getNewsPriority() {
		return this.newsPriority;
	}

	public void setNewsPriority(Integer newsPriority) {
		this.newsPriority = newsPriority;
	}

	@Column(name = "newsPublisher", length = 100)
	public String getNewsPublisher() {
		return this.newsPublisher;
	}

	public void setNewsPublisher(String newsPublisher) {
		this.newsPublisher = newsPublisher;
	}

	@Column(name = "newsClickNum")
	public Integer getNewsClickNum() {
		return this.newsClickNum;
	}

	public void setNewsClickNum(Integer newsClickNum) {
		this.newsClickNum = newsClickNum;
	}

	@Column(name = "newsType", length = 100)
	public String getNewsType() {
		return this.newsType;
	}

	public void setNewsType(String newsType) {
		this.newsType = newsType;
	}

	@Column(name = "reserve1", length = 100)
	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "reserve2", length = 100)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

}
