package com.whut.model;
// default package
// Generated 2019-5-13 20:26:26 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CommentInfo generated by hbm2java
 */
@Entity
@Table(name = "comment_info", catalog = "cloudtest")
public class CommentInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer commentId;
	private String commentAuthor;
	private String commentContent;
	private String commentTime;
	private Integer commentReplyId;
	private String commentReplyAuthor;
	private Integer commentFloorId;
	private String commentPicture;
	private Integer commentTopicId;
	private String reserve1;
	private String reserve2;

	public CommentInfo() {
	}

	public CommentInfo(String commentAuthor, String commentContent, String commentTime, Integer commentReplyId,
			String commentReplyAuthor, Integer commentFloorId, String commentPicture, Integer commentTopicId,
			String reserve1, String reserve2) {
		this.commentAuthor = commentAuthor;
		this.commentContent = commentContent;
		this.commentTime = commentTime;
		this.commentReplyId = commentReplyId;
		this.commentReplyAuthor = commentReplyAuthor;
		this.commentFloorId = commentFloorId;
		this.commentPicture = commentPicture;
		this.commentTopicId = commentTopicId;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "commentId", unique = true, nullable = false)
	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	@Column(name = "commentAuthor", length = 100)
	public String getCommentAuthor() {
		return this.commentAuthor;
	}

	public void setCommentAuthor(String commentAuthor) {
		this.commentAuthor = commentAuthor;
	}

	@Column(name = "commentContent", length = 65535)
	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	@Column(name = "commentTime", length = 50)
	public String getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(String commentTime) {
		this.commentTime = commentTime;
	}

	@Column(name = "commentReplyId")
	public Integer getCommentReplyId() {
		return this.commentReplyId;
	}

	public void setCommentReplyId(Integer commentReplyId) {
		this.commentReplyId = commentReplyId;
	}

	@Column(name = "commentReplyAuthor", length = 100)
	public String getCommentReplyAuthor() {
		return this.commentReplyAuthor;
	}

	public void setCommentReplyAuthor(String commentReplyAuthor) {
		this.commentReplyAuthor = commentReplyAuthor;
	}

	@Column(name = "commentFloorId")
	public Integer getCommentFloorId() {
		return this.commentFloorId;
	}

	public void setCommentFloorId(Integer commentFloorId) {
		this.commentFloorId = commentFloorId;
	}

	@Column(name = "commentPicture")
	public String getCommentPicture() {
		return this.commentPicture;
	}

	public void setCommentPicture(String commentPicture) {
		this.commentPicture = commentPicture;
	}

	@Column(name = "commentTopicId")
	public Integer getCommentTopicId() {
		return this.commentTopicId;
	}

	public void setCommentTopicId(Integer commentTopicId) {
		this.commentTopicId = commentTopicId;
	}

	@Column(name = "reserve1", length = 100)
	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "reserve2", length = 100)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

}
