package com.whut.model;
// default package
// Generated 2019-2-23 15:29:55 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "user_info", catalog = "cloudtest")
public class UserInfo implements java.io.Serializable {

	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String userAccount;
	private String userPassword;
	private String userNickname;
	private String userName;
	private String userSex;
	private String userJobtitle;
	private String userJob;
	private String userPhone;
	private String userIDnumber;
	private String userPhoto1;
	private String userPhoto2;
	private String userRegtime;
	private String userIntroduce;
	private String userLevel;
	private String userAccountstate;
	private String reserver1;
	private String reserver2;
	private String reserver3;
	private String reserver4;
	private String reserver5;

	public UserInfo() {
	}

	public UserInfo(String userAccount, String userPassword, String userNickname, String userName, String userSex,
			String userJobtitle, String userJob, String userPhone, String userIDnumber, String userPhoto1,
			String userPhoto2, String userRegtime, String userIntroduce, String userLevel, String userAccountstate,
			String reserver1, String reserver2, String reserver3, String reserver4, String reserver5) {
		this.userAccount = userAccount;
		this.userPassword = userPassword;
		this.userNickname = userNickname;
		this.userName = userName;
		this.userSex = userSex;
		this.userJobtitle = userJobtitle;
		this.userJob = userJob;
		this.userPhone = userPhone;
		this.userIDnumber = userIDnumber;
		this.userPhoto1 = userPhoto1;
		this.userPhoto2 = userPhoto2;
		this.userRegtime = userRegtime;
		this.userIntroduce = userIntroduce;
		this.userLevel = userLevel;
		this.userAccountstate = userAccountstate;
		this.reserver1 = reserver1;
		this.reserver2 = reserver2;
		this.reserver3 = reserver3;
		this.reserver4 = reserver4;
		this.reserver5 = reserver5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "userId", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "userAccount", length = 10)
	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	@Column(name = "userPassword", length = 70)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "userNickname", length = 30)
	public String getUserNickname() {
		return this.userNickname;
	}

	public void setUserNickname(String userNickname) {
		this.userNickname = userNickname;
	}

	@Column(name = "userName", length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "userSex", length = 5)
	public String getUserSex() {
		return this.userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	@Column(name = "userJobtitle", length = 20)
	public String getUserJobtitle() {
		return this.userJobtitle;
	}

	public void setUserJobtitle(String userJobtitle) {
		this.userJobtitle = userJobtitle;
	}

	@Column(name = "userJob", length = 100)
	public String getUserJob() {
		return this.userJob;
	}

	public void setUserJob(String userJob) {
		this.userJob = userJob;
	}

	@Column(name = "userPhone", length = 15)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "userIDnumber", length = 20)
	public String getUserIDnumber() {
		return this.userIDnumber;
	}

	public void setUserIDnumber(String userIDnumber) {
		this.userIDnumber = userIDnumber;
	}

	@Column(name = "userPhoto1")
	public String getUserPhoto1() {
		return this.userPhoto1;
	}

	public void setUserPhoto1(String userPhoto1) {
		this.userPhoto1 = userPhoto1;
	}

	@Column(name = "userPhoto2")
	public String getUserPhoto2() {
		return this.userPhoto2;
	}

	public void setUserPhoto2(String userPhoto2) {
		this.userPhoto2 = userPhoto2;
	}

	@Column(name = "userRegtime", length = 50)
	public String getUserRegtime() {
		return this.userRegtime;
	}

	public void setUserRegtime(String userRegtime) {
		this.userRegtime = userRegtime;
	}

	@Column(name = "userIntroduce", length = 65535)
	public String getUserIntroduce() {
		return this.userIntroduce;
	}

	public void setUserIntroduce(String userIntroduce) {
		this.userIntroduce = userIntroduce;
	}

	@Column(name = "userLevel", length = 20)
	public String getUserLevel() {
		return this.userLevel;
	}

	public void setUserLevel(String userLevel) {
		this.userLevel = userLevel;
	}

	@Column(name = "userAccountstate", length = 10)
	public String getUserAccountstate() {
		return this.userAccountstate;
	}

	public void setUserAccountstate(String userAccountstate) {
		this.userAccountstate = userAccountstate;
	}

	@Column(name = "Reserver1", length = 100)
	public String getReserver1() {
		return this.reserver1;
	}

	public void setReserver1(String reserver1) {
		this.reserver1 = reserver1;
	}

	@Column(name = "Reserver2", length = 100)
	public String getReserver2() {
		return this.reserver2;
	}

	public void setReserver2(String reserver2) {
		this.reserver2 = reserver2;
	}

	@Column(name = "Reserver3", length = 100)
	public String getReserver3() {
		return this.reserver3;
	}

	public void setReserver3(String reserver3) {
		this.reserver3 = reserver3;
	}

	@Column(name = "Reserver4", length = 100)
	public String getReserver4() {
		return this.reserver4;
	}

	public void setReserver4(String reserver4) {
		this.reserver4 = reserver4;
	}

	@Column(name = "Reserver5", length = 100)
	public String getReserver5() {
		return this.reserver5;
	}

	public void setReserver5(String reserver5) {
		this.reserver5 = reserver5;
	}

}
