package com.whut.model;
// default package
// Generated 2019-7-3 10:22:59 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VideoInfo generated by hbm2java
 */
@Entity
@Table(name = "video_info", catalog = "cloudtest")
public class VideoInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer videoId;
	private String videoName;
	private String videoIntroduce;
	private String videoContent;
	private String videoAuthor;
	private String videoAuthorId;
	private String videoUptime;
	private String videoRephoto;
	private String videoPhoto;
	private Integer videoPriority;
	private Double videoMark;
	private Integer videoCollectnum;
	private Integer videoTotalnum;
	private String reserve1;
	private String reserve2;
	private String reserve3;
	private String reserve4;
	private String reserve5;

	public VideoInfo() {
	}

	public VideoInfo(String videoName, String videoIntroduce, String videoContent, String videoAuthor,
			String videoAuthorId, String videoUptime, String videoRephoto, String videoPhoto, Integer videoPriority,
			Double videoMark, Integer videoCollectnum, Integer videoTotalnum, String reserve1, String reserve2,
			String reserve3, String reserve4, String reserve5) {
		this.videoName = videoName;
		this.videoIntroduce = videoIntroduce;
		this.videoContent = videoContent;
		this.videoAuthor = videoAuthor;
		this.videoAuthorId = videoAuthorId;
		this.videoUptime = videoUptime;
		this.videoRephoto = videoRephoto;
		this.videoPhoto = videoPhoto;
		this.videoPriority = videoPriority;
		this.videoMark = videoMark;
		this.videoCollectnum = videoCollectnum;
		this.videoTotalnum = videoTotalnum;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
		this.reserve4 = reserve4;
		this.reserve5 = reserve5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "videoId", unique = true, nullable = false)
	public Integer getVideoId() {
		return this.videoId;
	}

	public void setVideoId(Integer videoId) {
		this.videoId = videoId;
	}

	@Column(name = "videoName", length = 100)
	public String getVideoName() {
		return this.videoName;
	}

	public void setVideoName(String videoName) {
		this.videoName = videoName;
	}

	@Column(name = "videoIntroduce", length = 65535)
	public String getVideoIntroduce() {
		return this.videoIntroduce;
	}

	public void setVideoIntroduce(String videoIntroduce) {
		this.videoIntroduce = videoIntroduce;
	}

	@Column(name = "videoContent")
	public String getVideoContent() {
		return this.videoContent;
	}

	public void setVideoContent(String videoContent) {
		this.videoContent = videoContent;
	}

	@Column(name = "videoAuthor", length = 100)
	public String getVideoAuthor() {
		return this.videoAuthor;
	}

	public void setVideoAuthor(String videoAuthor) {
		this.videoAuthor = videoAuthor;
	}

	@Column(name = "videoAuthorId", length = 100)
	public String getVideoAuthorId() {
		return this.videoAuthorId;
	}

	public void setVideoAuthorId(String videoAuthorId) {
		this.videoAuthorId = videoAuthorId;
	}

	@Column(name = "videoUptime", length = 50)
	public String getVideoUptime() {
		return this.videoUptime;
	}

	public void setVideoUptime(String videoUptime) {
		this.videoUptime = videoUptime;
	}

	@Column(name = "videoRephoto")
	public String getVideoRephoto() {
		return this.videoRephoto;
	}

	public void setVideoRephoto(String videoRephoto) {
		this.videoRephoto = videoRephoto;
	}

	@Column(name = "videoPhoto")
	public String getVideoPhoto() {
		return this.videoPhoto;
	}

	public void setVideoPhoto(String videoPhoto) {
		this.videoPhoto = videoPhoto;
	}

	@Column(name = "videoPriority")
	public Integer getVideoPriority() {
		return this.videoPriority;
	}

	public void setVideoPriority(Integer videoPriority) {
		this.videoPriority = videoPriority;
	}

	@Column(name = "videoMark", precision = 5, scale = 1)
	public Double getVideoMark() {
		return this.videoMark;
	}

	public void setVideoMark(Double videoMark) {
		this.videoMark = videoMark;
	}

	@Column(name = "videoCollectnum")
	public Integer getVideoCollectnum() {
		return this.videoCollectnum;
	}

	public void setVideoCollectnum(Integer videoCollectnum) {
		this.videoCollectnum = videoCollectnum;
	}

	@Column(name = "videoTotalnum")
	public Integer getVideoTotalnum() {
		return this.videoTotalnum;
	}

	public void setVideoTotalnum(Integer videoTotalnum) {
		this.videoTotalnum = videoTotalnum;
	}

	@Column(name = "Reserve1", length = 100)
	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "Reserve2", length = 100)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	@Column(name = "Reserve3", length = 100)
	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	@Column(name = "Reserve4", length = 100)
	public String getReserve4() {
		return this.reserve4;
	}

	public void setReserve4(String reserve4) {
		this.reserve4 = reserve4;
	}

	@Column(name = "Reserve5", length = 100)
	public String getReserve5() {
		return this.reserve5;
	}

	public void setReserve5(String reserve5) {
		this.reserve5 = reserve5;
	}

}
