package com.whut.model;
// default package
// Generated 2019-3-2 12:46:38 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VideouserInfo generated by hbm2java
 */
@Entity
@Table(name = "videouser_info", catalog = "cloudtest")
public class VideouserInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer vuId;
	private Integer videoId;
	private Integer userId;
	private String reserver1;
	private String reserver2;

	public VideouserInfo() {
	}

	public VideouserInfo(Integer videoId, Integer userId, String reserver1, String reserver2) {
		this.videoId = videoId;
		this.userId = userId;
		this.reserver1 = reserver1;
		this.reserver2 = reserver2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "vuId", unique = true, nullable = false)
	public Integer getVuId() {
		return this.vuId;
	}

	public void setVuId(Integer vuId) {
		this.vuId = vuId;
	}

	@Column(name = "videoId")
	public Integer getVideoId() {
		return this.videoId;
	}

	public void setVideoId(Integer videoId) {
		this.videoId = videoId;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "reserver1", length = 100)
	public String getReserver1() {
		return this.reserver1;
	}

	public void setReserver1(String reserver1) {
		this.reserver1 = reserver1;
	}

	@Column(name = "reserver2", length = 100)
	public String getReserver2() {
		return this.reserver2;
	}

	public void setReserver2(String reserver2) {
		this.reserver2 = reserver2;
	}

}
