package com.whut.model;
// default package
// Generated 2019-3-2 12:46:38 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TextbookuserInfo generated by hbm2java
 */
@Entity
@Table(name = "textbookuser_info", catalog = "cloudtest")
public class TextbookuserInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer tuId;
	private Integer textbookId;
	private Integer userId;
	private String reserver1;
	private String reserver2;

	public TextbookuserInfo() {
	}

	public TextbookuserInfo(Integer textbookId, Integer userId, String reserver1, String reserver2) {
		this.textbookId = textbookId;
		this.userId = userId;
		this.reserver1 = reserver1;
		this.reserver2 = reserver2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tuId", unique = true, nullable = false)
	public Integer getTuId() {
		return this.tuId;
	}

	public void setTuId(Integer tuId) {
		this.tuId = tuId;
	}

	@Column(name = "textbookId")
	public Integer getTextbookId() {
		return this.textbookId;
	}

	public void setTextbookId(Integer textbookId) {
		this.textbookId = textbookId;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "reserver1", length = 100)
	public String getReserver1() {
		return this.reserver1;
	}

	public void setReserver1(String reserver1) {
		this.reserver1 = reserver1;
	}

	@Column(name = "reserver2", length = 100)
	public String getReserver2() {
		return this.reserver2;
	}

	public void setReserver2(String reserver2) {
		this.reserver2 = reserver2;
	}

}
