package com.whut.model;
// default package
// Generated 2019-2-23 15:29:55 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RelateInfo generated by hbm2java
 */
@Entity
@Table(name = "relate_info", catalog = "cloudtest")
public class RelateInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer relateId;
	private Integer courseId;
	private Integer textbookId;
	private Integer videoId;
	private String reserve1;
	private String reserve2;

	public RelateInfo() {
	}

	public RelateInfo(Integer courseId, Integer textbookId, Integer videoId, String reserve1, String reserve2) {
		this.courseId = courseId;
		this.textbookId = textbookId;
		this.videoId = videoId;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "relateId", unique = true, nullable = false)
	public Integer getRelateId() {
		return this.relateId;
	}

	public void setRelateId(Integer relateId) {
		this.relateId = relateId;
	}

	@Column(name = "courseId")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "textbookId")
	public Integer getTextbookId() {
		return this.textbookId;
	}

	public void setTextbookId(Integer textbookId) {
		this.textbookId = textbookId;
	}

	@Column(name = "videoId")
	public Integer getVideoId() {
		return this.videoId;
	}

	public void setVideoId(Integer videoId) {
		this.videoId = videoId;
	}

	@Column(name = "reserve1", length = 100)
	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "reserve2", length = 100)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

}
