package com.whut.model;
// default package
// Generated 2019-6-2 10:44:11 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TopicInfo generated by hbm2java
 */
@Entity
@Table(name = "topic_info", catalog = "cloudtest")
public class TopicInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer topicId;
	private String topicTitle;
	private String topicAuthor;
	private String topicContent;
	private Integer topicPriority;
	private String topicType1;
	private String topicType2;
	private String topicTime;
	private Integer topicNumber;
	private Integer topicAccessNumber;
	private String topicPicture;
	private String topicTop;
	private String reserve1;
	private String reserve2;

	public TopicInfo() {
	}

	public TopicInfo(String topicTitle, String topicAuthor, String topicContent, Integer topicPriority,
			String topicType1, String topicType2, String topicTime, Integer topicNumber, Integer topicAccessNumber,
			String topicPicture, String topicTop, String reserve1, String reserve2) {
		this.topicTitle = topicTitle;
		this.topicAuthor = topicAuthor;
		this.topicContent = topicContent;
		this.topicPriority = topicPriority;
		this.topicType1 = topicType1;
		this.topicType2 = topicType2;
		this.topicTime = topicTime;
		this.topicNumber = topicNumber;
		this.topicAccessNumber = topicAccessNumber;
		this.topicPicture = topicPicture;
		this.topicTop = topicTop;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "topicId", unique = true, nullable = false)
	public Integer getTopicId() {
		return this.topicId;
	}

	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	@Column(name = "topicTitle", length = 100)
	public String getTopicTitle() {
		return this.topicTitle;
	}

	public void setTopicTitle(String topicTitle) {
		this.topicTitle = topicTitle;
	}

	@Column(name = "topicAuthor", length = 50)
	public String getTopicAuthor() {
		return this.topicAuthor;
	}

	public void setTopicAuthor(String topicAuthor) {
		this.topicAuthor = topicAuthor;
	}

	@Column(name = "topicContent", length = 65535)
	public String getTopicContent() {
		return this.topicContent;
	}

	public void setTopicContent(String topicContent) {
		this.topicContent = topicContent;
	}

	@Column(name = "topicPriority")
	public Integer getTopicPriority() {
		return this.topicPriority;
	}

	public void setTopicPriority(Integer topicPriority) {
		this.topicPriority = topicPriority;
	}

	@Column(name = "topicType1", length = 100)
	public String getTopicType1() {
		return this.topicType1;
	}

	public void setTopicType1(String topicType1) {
		this.topicType1 = topicType1;
	}

	@Column(name = "topicType2", length = 100)
	public String getTopicType2() {
		return this.topicType2;
	}

	public void setTopicType2(String topicType2) {
		this.topicType2 = topicType2;
	}

	@Column(name = "topicTime", length = 50)
	public String getTopicTime() {
		return this.topicTime;
	}

	public void setTopicTime(String topicTime) {
		this.topicTime = topicTime;
	}

	@Column(name = "topicNumber")
	public Integer getTopicNumber() {
		return this.topicNumber;
	}

	public void setTopicNumber(Integer topicNumber) {
		this.topicNumber = topicNumber;
	}

	@Column(name = "topicAccessNumber")
	public Integer getTopicAccessNumber() {
		return this.topicAccessNumber;
	}

	public void setTopicAccessNumber(Integer topicAccessNumber) {
		this.topicAccessNumber = topicAccessNumber;
	}

	@Column(name = "topicPicture")
	public String getTopicPicture() {
		return this.topicPicture;
	}

	public void setTopicPicture(String topicPicture) {
		this.topicPicture = topicPicture;
	}

	@Column(name = "topicTop", length = 10)
	public String getTopicTop() {
		return this.topicTop;
	}

	public void setTopicTop(String topicTop) {
		this.topicTop = topicTop;
	}

	@Column(name = "reserve1", length = 100)
	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "reserve2", length = 100)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

}
