package com.whut.model;
// default package
// Generated 2019-2-23 15:29:55 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssessInfo generated by hbm2java
 */
@Entity
@Table(name = "assess_info", catalog = "cloudtest")
public class AssessInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer assessId;
	private String assessContent;
	private String assessTime;
	private Double assessMark;
	private Integer userId;
	private Integer courseId;
	private Integer textbookId;
	private Integer videoId;
	private String reserve1;
	private String reserve2;
	private String reserve3;
	private String reserve4;
	private String reserve5;

	public AssessInfo() {
	}

	public AssessInfo(String assessContent, String assessTime, Double assessMark, Integer userId, Integer courseId,
			Integer textbookId, Integer videoId, String reserve1, String reserve2, String reserve3, String reserve4,
			String reserve5) {
		this.assessContent = assessContent;
		this.assessTime = assessTime;
		this.assessMark = assessMark;
		this.userId = userId;
		this.courseId = courseId;
		this.textbookId = textbookId;
		this.videoId = videoId;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
		this.reserve4 = reserve4;
		this.reserve5 = reserve5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "assessId", unique = true, nullable = false)
	public Integer getAssessId() {
		return this.assessId;
	}

	public void setAssessId(Integer assessId) {
		this.assessId = assessId;
	}

	@Column(name = "assessContent", length = 65535)
	public String getAssessContent() {
		return this.assessContent;
	}

	public void setAssessContent(String assessContent) {
		this.assessContent = assessContent;
	}

	@Column(name = "assessTime", length = 50)
	public String getAssessTime() {
		return this.assessTime;
	}

	public void setAssessTime(String assessTime) {
		this.assessTime = assessTime;
	}

	@Column(name = "assessMark", precision = 5, scale = 1)
	public Double getAssessMark() {
		return this.assessMark;
	}

	public void setAssessMark(Double assessMark) {
		this.assessMark = assessMark;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "courseId")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "textbookId")
	public Integer getTextbookId() {
		return this.textbookId;
	}

	public void setTextbookId(Integer textbookId) {
		this.textbookId = textbookId;
	}

	@Column(name = "videoId")
	public Integer getVideoId() {
		return this.videoId;
	}

	public void setVideoId(Integer videoId) {
		this.videoId = videoId;
	}

	@Column(name = "Reserve1", length = 100)
	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "Reserve2", length = 100)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	@Column(name = "Reserve3", length = 100)
	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	@Column(name = "Reserve4", length = 100)
	public String getReserve4() {
		return this.reserve4;
	}

	public void setReserve4(String reserve4) {
		this.reserve4 = reserve4;
	}

	@Column(name = "Reserve5", length = 100)
	public String getReserve5() {
		return this.reserve5;
	}

	public void setReserve5(String reserve5) {
		this.reserve5 = reserve5;
	}

}
