package com.whut.model;
// default package
// Generated 2019-2-23 15:29:55 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CourseInfo generated by hbm2java
 */
@Entity
@Table(name = "course_info", catalog = "cloudtest")
public class CourseInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer courseId;
	private String courseName;
	private String courseIntroduce;
	private String courseOutline;
	private String courseAuthor;
	private String courseAim;
	private String courseStime;
	private String courseEtime;
	private String courseRephoto;
	private String coursePhoto;
	private Integer coursePeople;
	private Integer courseCollectnum;
	private Integer courseTotalnum;
	private Double courseMark;
	private String reserve1;
	private String reserve2;
	private String reserve3;
	private String reserve4;
	private String reserve5;

	public CourseInfo() {
	}

	public CourseInfo(String courseName, String courseIntroduce, String courseOutline, String courseAuthor,
			String courseAim, String courseStime, String courseEtime, String courseRephoto, String coursePhoto,
			Integer coursePeople, Integer courseCollectnum, Integer courseTotalnum, Double courseMark, String reserve1,
			String reserve2, String reserve3, String reserve4, String reserve5) {
		this.courseName = courseName;
		this.courseIntroduce = courseIntroduce;
		this.courseOutline = courseOutline;
		this.courseAuthor = courseAuthor;
		this.courseAim = courseAim;
		this.courseStime = courseStime;
		this.courseEtime = courseEtime;
		this.courseRephoto = courseRephoto;
		this.coursePhoto = coursePhoto;
		this.coursePeople = coursePeople;
		this.courseCollectnum = courseCollectnum;
		this.courseTotalnum = courseTotalnum;
		this.courseMark = courseMark;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
		this.reserve4 = reserve4;
		this.reserve5 = reserve5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "courseId", unique = true, nullable = false)
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "courseName", length = 100)
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@Column(name = "courseIntroduce", length = 65535)
	public String getCourseIntroduce() {
		return this.courseIntroduce;
	}

	public void setCourseIntroduce(String courseIntroduce) {
		this.courseIntroduce = courseIntroduce;
	}

	@Column(name = "courseOutline", length = 65535)
	public String getCourseOutline() {
		return this.courseOutline;
	}

	public void setCourseOutline(String courseOutline) {
		this.courseOutline = courseOutline;
	}

	@Column(name = "courseAuthor", length = 100)
	public String getCourseAuthor() {
		return this.courseAuthor;
	}

	public void setCourseAuthor(String courseAuthor) {
		this.courseAuthor = courseAuthor;
	}

	@Column(name = "courseAim", length = 65535)
	public String getCourseAim() {
		return this.courseAim;
	}

	public void setCourseAim(String courseAim) {
		this.courseAim = courseAim;
	}

	@Column(name = "courseStime", length = 50)
	public String getCourseStime() {
		return this.courseStime;
	}

	public void setCourseStime(String courseStime) {
		this.courseStime = courseStime;
	}

	@Column(name = "courseEtime", length = 50)
	public String getCourseEtime() {
		return this.courseEtime;
	}

	public void setCourseEtime(String courseEtime) {
		this.courseEtime = courseEtime;
	}

	@Column(name = "courseRephoto")
	public String getCourseRephoto() {
		return this.courseRephoto;
	}

	public void setCourseRephoto(String courseRephoto) {
		this.courseRephoto = courseRephoto;
	}

	@Column(name = "coursePhoto")
	public String getCoursePhoto() {
		return this.coursePhoto;
	}

	public void setCoursePhoto(String coursePhoto) {
		this.coursePhoto = coursePhoto;
	}

	@Column(name = "coursePeople")
	public Integer getCoursePeople() {
		return this.coursePeople;
	}

	public void setCoursePeople(Integer coursePeople) {
		this.coursePeople = coursePeople;
	}

	@Column(name = "courseCollectnum")
	public Integer getCourseCollectnum() {
		return this.courseCollectnum;
	}

	public void setCourseCollectnum(Integer courseCollectnum) {
		this.courseCollectnum = courseCollectnum;
	}

	@Column(name = "courseTotalnum")
	public Integer getCourseTotalnum() {
		return this.courseTotalnum;
	}

	public void setCourseTotalnum(Integer courseTotalnum) {
		this.courseTotalnum = courseTotalnum;
	}

	@Column(name = "courseMark", precision = 5, scale = 1)
	public Double getCourseMark() {
		return this.courseMark;
	}

	public void setCourseMark(Double courseMark) {
		this.courseMark = courseMark;
	}

	@Column(name = "Reserve1", length = 100)
	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "Reserve2", length = 100)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	@Column(name = "Reserve3", length = 100)
	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	@Column(name = "Reserve4", length = 100)
	public String getReserve4() {
		return this.reserve4;
	}

	public void setReserve4(String reserve4) {
		this.reserve4 = reserve4;
	}

	@Column(name = "Reserve5", length = 100)
	public String getReserve5() {
		return this.reserve5;
	}

	public void setReserve5(String reserve5) {
		this.reserve5 = reserve5;
	}

}
