package com.whut.model;
// default package
// Generated 2019-5-8 10:51:44 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ModuleInfo generated by hbm2java
 */
@Entity
@Table(name = "module_info", catalog = "cloudtest")
public class ModuleInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer moduleId;
	private String moduleName;
	private String moduleRely;
	private Integer modulePriority;
	private String reserve1;
	private String reserve2;

	public ModuleInfo() {
	}

	public ModuleInfo(String moduleName, String moduleRely, Integer modulePriority, String reserve1, String reserve2) {
		this.moduleName = moduleName;
		this.moduleRely = moduleRely;
		this.modulePriority = modulePriority;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "moduleId", unique = true, nullable = false)
	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "moduleName", length = 100)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "moduleRely", length = 100)
	public String getModuleRely() {
		return this.moduleRely;
	}

	public void setModuleRely(String moduleRely) {
		this.moduleRely = moduleRely;
	}

	@Column(name = "modulePriority")
	public Integer getModulePriority() {
		return this.modulePriority;
	}

	public void setModulePriority(Integer modulePriority) {
		this.modulePriority = modulePriority;
	}

	@Column(name = "reserve1", length = 100)
	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "reserve2", length = 100)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

}
