package com.whut.model;
// default package
// Generated 2019-7-8 15:35:58 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RecommandInfo generated by hbm2java
 */
@Entity
@Table(name = "recommand_info", catalog = "cloudtest")
public class RecommandInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer recommandId;
	private Integer courseId;
	private Integer textbookId;
	private Integer videoId;
	private String recommandLevel;
	private String recommandTime;
	private String recommandstate;
	private String recommandPicture;
	private String reserve1;
	private String reserve2;
	private String reserve3;
	private String reserve4;
	private String reserve5;

	public RecommandInfo() {
	}

	public RecommandInfo(Integer courseId, Integer textbookId, Integer videoId, String recommandLevel,
			String recommandTime, String recommandstate, String recommandPicture, String reserve1, String reserve2,
			String reserve3, String reserve4, String reserve5) {
		this.courseId = courseId;
		this.textbookId = textbookId;
		this.videoId = videoId;
		this.recommandLevel = recommandLevel;
		this.recommandTime = recommandTime;
		this.recommandstate = recommandstate;
		this.recommandPicture = recommandPicture;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
		this.reserve4 = reserve4;
		this.reserve5 = reserve5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recommandId", unique = true, nullable = false)
	public Integer getRecommandId() {
		return this.recommandId;
	}

	public void setRecommandId(Integer recommandId) {
		this.recommandId = recommandId;
	}

	@Column(name = "courseId")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "textbookId")
	public Integer getTextbookId() {
		return this.textbookId;
	}

	public void setTextbookId(Integer textbookId) {
		this.textbookId = textbookId;
	}

	@Column(name = "videoId")
	public Integer getVideoId() {
		return this.videoId;
	}

	public void setVideoId(Integer videoId) {
		this.videoId = videoId;
	}

	@Column(name = "recommandLevel", length = 20)
	public String getRecommandLevel() {
		return this.recommandLevel;
	}

	public void setRecommandLevel(String recommandLevel) {
		this.recommandLevel = recommandLevel;
	}

	@Column(name = "recommandTime", length = 50)
	public String getRecommandTime() {
		return this.recommandTime;
	}

	public void setRecommandTime(String recommandTime) {
		this.recommandTime = recommandTime;
	}

	@Column(name = "recommandstate", length = 10)
	public String getRecommandstate() {
		return this.recommandstate;
	}

	public void setRecommandstate(String recommandstate) {
		this.recommandstate = recommandstate;
	}

	@Column(name = "recommandPicture")
	public String getRecommandPicture() {
		return this.recommandPicture;
	}

	public void setRecommandPicture(String recommandPicture) {
		this.recommandPicture = recommandPicture;
	}

	@Column(name = "Reserve1", length = 100)
	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "Reserve2", length = 100)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	@Column(name = "Reserve3", length = 100)
	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	@Column(name = "Reserve4", length = 100)
	public String getReserve4() {
		return this.reserve4;
	}

	public void setReserve4(String reserve4) {
		this.reserve4 = reserve4;
	}

	@Column(name = "Reserve5", length = 100)
	public String getReserve5() {
		return this.reserve5;
	}

	public void setReserve5(String reserve5) {
		this.reserve5 = reserve5;
	}

}
