package com.whut.model;
// default package
// Generated 2019-7-8 8:51:58 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TeamInfo generated by hbm2java
 */
@Entity
@Table(name = "team_info", catalog = "cloudtest")
public class TeamInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer teamId;
	private String teamTitle;
	private String teamContent;
	private Integer teamPriority;
	private String teamInstitution;
	private String teamType;
	private String teamLeader1;
	private String teamLeader2;
	private String teamMember;
	private String reserve1;
	private String reserve2;

	public TeamInfo() {
	}

	public TeamInfo(String teamTitle, String teamContent, Integer teamPriority, String teamInstitution, String teamType,
			String teamLeader1, String teamLeader2, String teamMember, String reserve1, String reserve2) {
		this.teamTitle = teamTitle;
		this.teamContent = teamContent;
		this.teamPriority = teamPriority;
		this.teamInstitution = teamInstitution;
		this.teamType = teamType;
		this.teamLeader1 = teamLeader1;
		this.teamLeader2 = teamLeader2;
		this.teamMember = teamMember;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "teamId", unique = true, nullable = false)
	public Integer getTeamId() {
		return this.teamId;
	}

	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	@Column(name = "teamTitle", length = 100)
	public String getTeamTitle() {
		return this.teamTitle;
	}

	public void setTeamTitle(String teamTitle) {
		this.teamTitle = teamTitle;
	}

	@Column(name = "teamContent", length = 65535)
	public String getTeamContent() {
		return this.teamContent;
	}

	public void setTeamContent(String teamContent) {
		this.teamContent = teamContent;
	}

	@Column(name = "teamPriority")
	public Integer getTeamPriority() {
		return this.teamPriority;
	}

	public void setTeamPriority(Integer teamPriority) {
		this.teamPriority = teamPriority;
	}

	@Column(name = "teamInstitution", length = 100)
	public String getTeamInstitution() {
		return this.teamInstitution;
	}

	public void setTeamInstitution(String teamInstitution) {
		this.teamInstitution = teamInstitution;
	}

	@Column(name = "teamType", length = 100)
	public String getTeamType() {
		return this.teamType;
	}

	public void setTeamType(String teamType) {
		this.teamType = teamType;
	}

	@Column(name = "teamLeader1", length = 100)
	public String getTeamLeader1() {
		return this.teamLeader1;
	}

	public void setTeamLeader1(String teamLeader1) {
		this.teamLeader1 = teamLeader1;
	}

	@Column(name = "teamLeader2", length = 100)
	public String getTeamLeader2() {
		return this.teamLeader2;
	}

	public void setTeamLeader2(String teamLeader2) {
		this.teamLeader2 = teamLeader2;
	}

	@Column(name = "teamMember")
	public String getTeamMember() {
		return this.teamMember;
	}

	public void setTeamMember(String teamMember) {
		this.teamMember = teamMember;
	}

	@Column(name = "reserve1", length = 100)
	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "reserve2", length = 100)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

}
