package com.whut.model;
// default package
// Generated 2019-7-6 15:29:16 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TextbookInfo generated by hbm2java
 */
@Entity
@Table(name = "textbook_info", catalog = "cloudtest")
public class TextbookInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer textbookId;
	private String textbookName;
	private String textbookIntroduce;
	private String textbookOutline;
	private String textbookContent;
	private String textbookAuthor;
	private String textbookAuthorName;
	private Integer textbookPriority;
	private String textbookPublic;
	private String textbookPublictime;
	private String textbookPublicadd;
	private String textbookRephoto;
	private String textbookPhoto;
	private Integer textbookCollectnum;
	private Double textbookAssessmark;
	private Integer textbookClickNum;
	private String reserve1;
	private String reserve2;
	private String reserve3;
	private String reserve4;
	private String reserve5;

	public TextbookInfo() {
	}

	public TextbookInfo(String textbookName, String textbookIntroduce, String textbookOutline, String textbookContent,
			String textbookAuthor, String textbookAuthorName, Integer textbookPriority, String textbookPublic,
			String textbookPublictime, String textbookPublicadd, String textbookRephoto, String textbookPhoto,
			Integer textbookCollectnum, Double textbookAssessmark, Integer textbookClickNum, String reserve1,
			String reserve2, String reserve3, String reserve4, String reserve5) {
		this.textbookName = textbookName;
		this.textbookIntroduce = textbookIntroduce;
		this.textbookOutline = textbookOutline;
		this.textbookContent = textbookContent;
		this.textbookAuthor = textbookAuthor;
		this.textbookAuthorName = textbookAuthorName;
		this.textbookPriority = textbookPriority;
		this.textbookPublic = textbookPublic;
		this.textbookPublictime = textbookPublictime;
		this.textbookPublicadd = textbookPublicadd;
		this.textbookRephoto = textbookRephoto;
		this.textbookPhoto = textbookPhoto;
		this.textbookCollectnum = textbookCollectnum;
		this.textbookAssessmark = textbookAssessmark;
		this.textbookClickNum = textbookClickNum;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
		this.reserve4 = reserve4;
		this.reserve5 = reserve5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "textbookId", unique = true, nullable = false)
	public Integer getTextbookId() {
		return this.textbookId;
	}

	public void setTextbookId(Integer textbookId) {
		this.textbookId = textbookId;
	}

	@Column(name = "textbookName", length = 100)
	public String getTextbookName() {
		return this.textbookName;
	}

	public void setTextbookName(String textbookName) {
		this.textbookName = textbookName;
	}

	@Column(name = "textbookIntroduce", length = 65535)
	public String getTextbookIntroduce() {
		return this.textbookIntroduce;
	}

	public void setTextbookIntroduce(String textbookIntroduce) {
		this.textbookIntroduce = textbookIntroduce;
	}

	@Column(name = "textbookOutline", length = 65535)
	public String getTextbookOutline() {
		return this.textbookOutline;
	}

	public void setTextbookOutline(String textbookOutline) {
		this.textbookOutline = textbookOutline;
	}

	@Column(name = "textbookContent")
	public String getTextbookContent() {
		return this.textbookContent;
	}

	public void setTextbookContent(String textbookContent) {
		this.textbookContent = textbookContent;
	}

	@Column(name = "textbookAuthor", length = 100)
	public String getTextbookAuthor() {
		return this.textbookAuthor;
	}

	public void setTextbookAuthor(String textbookAuthor) {
		this.textbookAuthor = textbookAuthor;
	}

	@Column(name = "textbookAuthorName", length = 100)
	public String getTextbookAuthorName() {
		return this.textbookAuthorName;
	}

	public void setTextbookAuthorName(String textbookAuthorName) {
		this.textbookAuthorName = textbookAuthorName;
	}

	@Column(name = "textbookPriority")
	public Integer getTextbookPriority() {
		return this.textbookPriority;
	}

	public void setTextbookPriority(Integer textbookPriority) {
		this.textbookPriority = textbookPriority;
	}

	@Column(name = "textbookPublic", length = 100)
	public String getTextbookPublic() {
		return this.textbookPublic;
	}

	public void setTextbookPublic(String textbookPublic) {
		this.textbookPublic = textbookPublic;
	}

	@Column(name = "textbookPublictime", length = 50)
	public String getTextbookPublictime() {
		return this.textbookPublictime;
	}

	public void setTextbookPublictime(String textbookPublictime) {
		this.textbookPublictime = textbookPublictime;
	}

	@Column(name = "textbookPublicadd", length = 50)
	public String getTextbookPublicadd() {
		return this.textbookPublicadd;
	}

	public void setTextbookPublicadd(String textbookPublicadd) {
		this.textbookPublicadd = textbookPublicadd;
	}

	@Column(name = "textbookRephoto")
	public String getTextbookRephoto() {
		return this.textbookRephoto;
	}

	public void setTextbookRephoto(String textbookRephoto) {
		this.textbookRephoto = textbookRephoto;
	}

	@Column(name = "textbookPhoto")
	public String getTextbookPhoto() {
		return this.textbookPhoto;
	}

	public void setTextbookPhoto(String textbookPhoto) {
		this.textbookPhoto = textbookPhoto;
	}

	@Column(name = "textbookCollectnum")
	public Integer getTextbookCollectnum() {
		return this.textbookCollectnum;
	}

	public void setTextbookCollectnum(Integer textbookCollectnum) {
		this.textbookCollectnum = textbookCollectnum;
	}

	@Column(name = "textbookAssessmark", precision = 5, scale = 1)
	public Double getTextbookAssessmark() {
		return this.textbookAssessmark;
	}

	public void setTextbookAssessmark(Double textbookAssessmark) {
		this.textbookAssessmark = textbookAssessmark;
	}

	@Column(name = "textbookClickNum")
	public Integer getTextbookClickNum() {
		return this.textbookClickNum;
	}

	public void setTextbookClickNum(Integer textbookClickNum) {
		this.textbookClickNum = textbookClickNum;
	}

	@Column(name = "Reserve1", length = 100)
	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "Reserve2", length = 100)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	@Column(name = "Reserve3", length = 100)
	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	@Column(name = "Reserve4", length = 100)
	public String getReserve4() {
		return this.reserve4;
	}

	public void setReserve4(String reserve4) {
		this.reserve4 = reserve4;
	}

	@Column(name = "Reserve5", length = 100)
	public String getReserve5() {
		return this.reserve5;
	}

	public void setReserve5(String reserve5) {
		this.reserve5 = reserve5;
	}

}
